name: Login Certificates
description: Creates certificate files from Base64 string
inputs:
  signing-certificate-content:
    required: true
    description: The signing certificate in base64 encoded string
  encryption-certificate-content:
    required: true
    description: The encryption certificate in base64 encoded string
  target-dir:
    required: true
    descritpion: The folder where to store the certificate files

runs:
  using: composite
  steps:
    - name: Create Signing Certificate
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'signing-certificate.pfx'
        fileDir: ${{ inputs.target-dir }}
        encodedString: ${{ inputs.signing-certificate-content }}
    - name: Create Encryption Certificate
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'encryption-certificate.pfx'
        fileDir: ${{ inputs.target-dir }}
        encodedString: ${{ inputs.encryption-certificate-content }}
