name: CI-CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          role-session-name: OIDCSession

      - name: Setup .NET Core SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Setup CDK
        run: npm install -g aws-cdk

      - name: CDK Bootstrap
        run: cdk bootstrap
      - name: CDK Deploy
        run: cdk deploy --require-approval never --all
